"""initial schema

Revision ID: 2cc5396af21a
Revises: 
Create Date: 2026-08-04 21:15:08.817771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cc5396af21a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('methodology',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('middleware_definition',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('class_path', sa.String(length=512), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_definition',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_model_name')
    )
    op.create_table('skill_definition',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_skill_name')
    )
    op.create_table('tool_definition',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tool_type', sa.String(length=32), nullable=False),
    sa.Column('class_path', sa.String(length=512), nullable=True),
    sa.Column('input_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('output_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_definition',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_definition.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_agent_name')
    )
    with op.batch_alter_table('agent_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_definition_model_id'), ['model_id'], unique=False)

    op.create_table('conversation',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('methodology_id', sa.String(length=128), nullable=False),
    sa.Column('methodology_version', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_thread_id'), ['thread_id'], unique=True)

    op.create_table('methodology_revision',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('methodology_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodology.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('methodology_id', 'version', name='uq_methodology_revision')
    )
    op.create_table('agent_middleware',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('middleware_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['middleware_id'], ['middleware_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'middleware_id')
    )
    op.create_table('agent_skill',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id')
    )
    op.create_table('agent_tool',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    op.create_table('methodology_agent',
    sa.Column('methodology_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodology.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('methodology_id', 'agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('methodology_agent')
    op.drop_table('agent_tool')
    op.drop_table('agent_skill')
    op.drop_table('agent_middleware')
    op.drop_table('methodology_revision')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_thread_id'))

    op.drop_table('conversation')
    with op.batch_alter_table('agent_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_definition_model_id'))

    op.drop_table('agent_definition')
    op.drop_table('tool_definition')
    op.drop_table('skill_definition')
    op.drop_table('model_definition')
    op.drop_table('middleware_definition')
    op.drop_table('methodology')
    # ### end Alembic commands ###
