"""initial_schema

Revision ID: c960f621dfd0
Revises: 
Create Date: 2026-08-09 22:14:14.424114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c960f621dfd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_blob',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('methodology',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_methodology_owner_name')
    )
    with op.batch_alter_table('methodology', schema=None) as batch_op:
        batch_op.create_index('ix_methodology_owner_updated_id', ['owner_user_id', 'updated_time', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_methodology_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('middleware_definition',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('class_path', sa.String(length=512), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_middleware_owner_name')
    )
    with op.batch_alter_table('middleware_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_middleware_definition_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('model_definition',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_model_owner_name')
    )
    with op.batch_alter_table('model_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_definition_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('skill_definition',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_skill_owner_name')
    )
    with op.batch_alter_table('skill_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_definition_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('tool_definition',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tool_type', sa.String(length=32), nullable=False),
    sa.Column('class_path', sa.String(length=512), nullable=True),
    sa.Column('requires_hitl', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_tool_owner_name')
    )
    with op.batch_alter_table('tool_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_definition_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('agent_definition',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_definition.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_agent_owner_name')
    )
    with op.batch_alter_table('agent_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_definition_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_definition_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('conversation',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('methodology_id', sa.String(length=128), nullable=False),
    sa.Column('methodology_version', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodology.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'thread_id', name='uq_conversation_user_thread')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_methodology_id'), ['methodology_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index('ix_conversation_user_created_id', ['user_id', 'created_time', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_user_id'), ['user_id'], unique=False)

    op.create_table('methodology_revision',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('methodology_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodology.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('methodology_id', 'version', name='uq_methodology_revision')
    )
    op.create_table('agent_middleware',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('middleware_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['middleware_id'], ['middleware_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'middleware_id')
    )
    with op.batch_alter_table('agent_middleware', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_middleware_middleware_id'), ['middleware_id'], unique=False)

    op.create_table('agent_skill',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id')
    )
    with op.batch_alter_table('agent_skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_skill_skill_id'), ['skill_id'], unique=False)

    op.create_table('agent_tool',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    with op.batch_alter_table('agent_tool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tool_tool_id'), ['tool_id'], unique=False)

    op.create_table('methodology_agent',
    sa.Column('methodology_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodology.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('methodology_id', 'agent_id')
    )
    with op.batch_alter_table('methodology_agent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_methodology_agent_agent_id'), ['agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('methodology_agent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_methodology_agent_agent_id'))

    op.drop_table('methodology_agent')
    with op.batch_alter_table('agent_tool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tool_tool_id'))

    op.drop_table('agent_tool')
    with op.batch_alter_table('agent_skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_skill_skill_id'))

    op.drop_table('agent_skill')
    with op.batch_alter_table('agent_middleware', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_middleware_middleware_id'))

    op.drop_table('agent_middleware')
    op.drop_table('methodology_revision')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_user_id'))
        batch_op.drop_index('ix_conversation_user_created_id')
        batch_op.drop_index(batch_op.f('ix_conversation_thread_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_methodology_id'))

    op.drop_table('conversation')
    with op.batch_alter_table('agent_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_definition_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_definition_model_id'))

    op.drop_table('agent_definition')
    with op.batch_alter_table('tool_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_definition_owner_user_id'))

    op.drop_table('tool_definition')
    with op.batch_alter_table('skill_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_definition_owner_user_id'))

    op.drop_table('skill_definition')
    with op.batch_alter_table('model_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_definition_owner_user_id'))

    op.drop_table('model_definition')
    with op.batch_alter_table('middleware_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_middleware_definition_owner_user_id'))

    op.drop_table('middleware_definition')
    with op.batch_alter_table('methodology', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_methodology_owner_user_id'))
        batch_op.drop_index('ix_methodology_owner_updated_id')

    op.drop_table('methodology')
    op.drop_table('content_blob')
    # ### end Alembic commands ###
